### ISSUE TITLE
Pro Players:  Nemsemsei: Twitter

### ISSUE THREAD

**Issue by jbooruiz** [RoyaleAPI/cr-api-ux#114]
Nemsemsei (https://royaleapi.com/player/2RU2JC90) has Twitter at https://twitter.com/Nemsenpai

**Comment by alpe123** [comment]
Updated.
@jbooruiz maybe you'd prefer using our forms instead of filing GitHub issues.

"If you wish to be added to the list of professional players or want to update your information, please fill out this form. 
English: https://t.co/4BVskQOQ35 
Español: https://t.co/b6w2tYpqgc 

Thanks!"

**Comment by jbooruiz** [comment]
Yes, I saw that later!
