### ISSUE TITLE
clan endpoint donations not right compared to CR live

### ISSUE THREAD

**Issue by gabebor** [RoyaleAPI/cr-api-ux#121]
live i have now 20180604 20:08:00 112 donations
clan endpoint have wrong donations:
{'name': 'bobbelsche', 'tag': '2V22909Q', 'rank': 8, 'previousRank': 2, 'role': 'coLeader', 'expLevel': 12, 'trophies': 4000, 'clanChestCrowns': 88, 'donations': 170, 'donationsReceived': 80, 'donationsDelta': 90, 'arena': {'name': 'Challenger I', 'arena': 'League 1', 'arenaID': 13, 'trophyLimit': 4000}, 'donationsPercent': 3.53}

**Comment by fourjr** [comment]
Is this the API or the website?

**Comment by gabebor** [comment]
it is about the API compared to the live information from CR Game,
but you can close this issue... i looks like my CR (runs on PC within android emulator) did not updated right ;). sorry for inconvenience

**Comment by fourjr** [comment]
Please create an issue on RoyaleAPI/cr-api next time if it is regarding the API
