### ISSUE TITLE
Getting 429 (too many requests)

### ISSUE THREAD

**Issue by briankates816** [RoyaleAPI/cr-api-ux#160]
I started getting 429 exceptions on the 22nd.  I check my logs and I made five requests in five seconds.  On the requests that come back, the header info shows zero requests left and a rate limit reset of the current time.  I cannot make any requests to the API using my key.

**Comment by fourjr** [comment]
This issue was moved to RoyaleAPI/cr-api#384

**Comment by fourjr** [comment]
Please open issues regarding the API on the other repository
