### ISSUE TITLE
War log bug: abandoned and loss during war was not registered. 

### ISSUE THREAD

**Issue by ayoitsLuke** [RoyaleAPI/cr-api-ux#163]
As circled in red, the clanmate named "me" had two chances to battle during a war. He lost one but abandoned the other one. However, API registered it as only one loss. My apologies for the long screenshots, just to prove it's the same war of the same clan by including more players. 

The first screenshot is from official CR client. The second one was captured from API website. 

**_Attachments:_**
**First Screenshot (From SuperCell ClashRoayle android client)**
![cr_client](https://user-images.githubusercontent.com/40584729/41884192-4bc64c74-78c0-11e8-9c49-7f925e383c9b.png)

**Second Screenshot (screen captured from API website.)**
![cr_apiweb](https://user-images.githubusercontent.com/40584729/41884194-4ed4c026-78c0-11e8-827b-9d3016a7ae61.png)

**Comment by fourjr** [comment]
The API doesn't provide the available battle count (re: #333). Since he abandoned the second battle, neither the API nor the UX website has knowledge of that. If he did the second battle, the api should track that.

**Comment by fourjr** [comment]
The API doesn't provide the available battle count (re: #333). Since he abandoned the second battle, neither the API nor the UX website has knowledge of that. If he did the second battle, the api should track that.

**Comment by ayoitsLuke** [comment]
thanks
