### ISSUE TITLE
War history results not populating at bottom of player profile when they do show up within analytics for when player was in clan earlier and analytics were repeatedly retrieved

### ISSUE THREAD

**Issue by ijm8710** [RoyaleAPI/cr-api-ux#360]
![GitHawk Upload by ijm8710](https://i.imgur.com/3DgJELP.jpg)
![GitHawk Upload by ijm8710](https://i.imgur.com/kriUqEg.jpg)

https://royaleapi.com/player/YQVV0VUG

**Comment by ijm8710** [comment]
![GitHawk Upload by ijm8710](https://i.imgur.com/3DgJELP.jpg)
![GitHawk Upload by ijm8710](https://i.imgur.com/kriUqEg.jpg)

**Comment by ijm8710** [comment]
https://royaleapi.com/clan/PCY2YQ0C/war/analytics

^what would be reason for his former clan no having results populate for its members?

**Comment by ijm87102** [comment]
Test
