### ISSUE TITLE
Ability to import clan data to Google Sheets

### ISSUE THREAD

**Issue by RippedAmoeba** [RoyaleAPI/cr-api-ux#42]
It would be easier to manage a clan if we can get latest data like the members, rank, donations and crowns on a google spreadsheet every week.
Just a thought.
Thank you

**Comment by selfish** [comment]
You can do it on your end, from google sheets.
Just pull the data..

**Comment by RippedAmoeba** [comment]
Could you help me with that? I have no idea

**Comment by Gr8z** [comment]
@RippedAmoeba DM me on discord, I can help you out.
